function xWF = cmm_xWF_func(x,T1,T2)
%matlabFunction(xWF,'File','cmm_xWF_func')生成;
L11 = x(1);
L12 = x(2);
L21 = x(3);
L22 = x(4);
D   = x(5);
L23 = x(6);
GAMA= x(7);
DELTA1 = x(8);
DELTA2 = x(9);
X0 = x(10);
Y0 = x(11);
ALPHA = x(12);
%XWF_FUNC
%    XWF = XWF_FUNC(ALPHA,DELTA1,DELTA2,D,GAMA,L11,L12,L21,L22,L23,T1,T2,X0)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    28-Apr-2025 13:52:59

t2 = DELTA2+T2;
t3 = sin(t2);
t4 = L21.*t3;
t5 = DELTA1+T1;
t10 = cos(t5);
t11 = L11.*t10;
t12 = cos(t2);
t13 = L21.*t12;
t6 = D-t11+t13;
t7 = sin(t5);
t8 = L11.*t7;
t9 = t4-t8;
t14 = t6.^2;
t15 = -t4+t8;
t16 = t15.^2;
t17 = t14+t16;
t18 = L12.^2;
t19 = L22.^2;
t20 = t14+t16+t18-t19;
t21 = 1.0./L22;
t22 = 1.0./sqrt(t17);
t23 = 1.0./t17;
t24 = t20.^2;
t28 = (t23.*t24)./4.0;
t25 = t18-t28;
t26 = sqrt(t25);
t27 = sin(GAMA);
t29 = cos(GAMA);
t30 = t15.*t22.*t26;
t31 = (t6.*t20.*t23)./2.0;
t32 = -D+t11-t13+t30+t31;
xWF = X0-sin(ALPHA).*(t4+L23.*t21.*t27.*t32-L23.*t21.*t29.*(t4-t8+(t15.*t20)./(t14.*2.0+t9.^2.*2.0)-t6.*t22.*t26))+cos(ALPHA).*(D./2.0+t13+L23.*t21.*t29.*t32+L23.*t21.*t27.*(t4-t8-t6.*t22.*t26+(t15.*t20.*t23)./2.0));
