function Fx = eag(x)
%aggregated pose error vector
global measures_ag t1s t2s;
Fx = zeros(size(measures_ag));
samples = length(measures_ag) / 2;

%cose1_func: Generated by matlabFunction
Fx(1:samples) = measures_ag(1:samples) - cose1_func(x, t1s, t2s);
Fx(samples + 1:2*samples) = measures_ag(samples + 1:2*samples) - cose2_func(x, t1s, t2s);
end


