function cose2 = self_cose2_func(x,T1,T2)
%D=200 matlabFunction(COSE2, 'File', 'self_cose1_func')生成
L11 = x(1);
L12 = x(2);
L21 = x(3);
L22 = x(4);
DELTA1 = x(5);
DELTA2 = x(6);
DELTA3 = x(7);
DELTA4 = x(8);
%COSE2_FUNC
%    COSE2 = COSE2_FUNC(DELTA1,DELTA2,DELTA4,L11,L12,L21,L22,T1,T2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    03-Apr-2025 15:34:14

t2 = DELTA2+T2;
t3 = cos(t2);
t4 = DELTA1+T1;
t5 = cos(t4);
t6 = L11.*t5;
t9 = L21.*t3;
t7 = -t6+t9+2.0e2;
t11 = sin(t4);
t12 = L11.*t11;
t13 = sin(t2);
t14 = L21.*t13;
t8 = t12-t14;
t10 = t7.^2;
t15 = t8.^2;
t16 = t10+t15;
t17 = 1.0./t16;
t18 = L12.^2;
t19 = L22.^2;
t20 = t10+t15+t18-t19;
t21 = 1.0./sqrt(t16);
t22 = t20.^2;
t27 = (t17.*t22)./4.0;
t23 = t18-t27;
t24 = sqrt(t23);
t26 = (t7.*t17.*t20)./2.0;
t28 = t8.*t21.*t24;
t29 = (t8.*t17.*t20)./2.0;
t30 = t7.*t21.*t24;
t31 = t12-t14-t29+t30;
t32 = L21.*t13.*t31;
t25 = t32+L21.*t3.*(t6+t26+t28-L21.*t3-2.0e2);
cose2 = sin(DELTA4).*sqrt(-1.0./L21.^2.*1.0./L22.^2.*t25.^2+1.0)-(cos(DELTA4).*(t32+L21.*t3.*(t6-t9+t26+t28-2.0e2)))./(L21.*L22);
