function Fx = self_eag3(x)
%aggregated pose error vector for 3 encoders
global measures_ag t1s t2s;
Fx = zeros(size(measures_ag));
samples = length(measures_ag);  %测量次数

%cose1_func: Generated by matlabFunction
Fx(1:samples) = measures_ag(1:samples) - self_cose1_func(x, t1s, t2s);  %COSE1 Error Vector
end


