function Fx = self_eag(x)
%aggregated pose error vector for 4 encoders
global measures_ag t1s t2s;
Fx = zeros(size(measures_ag));
samples = length(measures_ag) / 2;  %测量次数

%cose1_func: Generated by matlabFunction
Fx(1:samples) = measures_ag(1:samples) - self_cose1_func(x, t1s, t2s);  %COSE1 Error Vector
Fx(samples + 1:2*samples) = measures_ag(samples + 1:2*samples) - self_cose2_func(x, t1s, t2s); %COSE2 Error Vector
end


